sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib install monsoon-embed
  - haxelib run travix install

script:
  - haxelib run travix php
  - haxelib run travix neko
  - haxelib run travix node
  - haxelib run travix java -lib monsoon-embed
  - haxelib run travix cpp -lib monsoon-embed